{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rstuf-webapp.serviceAccountName" . }}
  labels:
    {{- include "rstuf-webapp.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
# This service calls nothing in the Kubernetes API, so it is given no
# credentials for it.
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
